### PR TITLE
Updated readme.md

### PR DESCRIPTION
**Pull request by smartnavdeep**
Hi Ved, I am Navdeep and I actually liked your idea of making the repository

Now I'm not big enough to tell you but the documentation is not looking good.

That is why I forked your repo and made the documentation look better.

Another thing I wanted to mention is the Status of the repository

I mean, it is better to mention that what ever you have developed is checked and is ready to use or if you are still developing it, then you should mention "Still in development, not ready to use"  in the documentation (README.md file)

I have not edited any of your files except the README.md (the documentation file)

Please take the pull request if you consider it help-full and if you did like the idea and you merged the request, then you can believe me that I would not do anything to your code.

Here is how the documentation will look like :
________________________________________________________________________________________________________________________________________

# Login System

## About

*A Login System Made with Python 3*

## How it Works:

-  It has an image,data.txt, hashing.py, login.py, login_gui.py, main.py, signup.py, sign_up_gui.py, checks.py files.

-  The image is displayed on the front, when the user clicks on the login button the login_gui file is called and when the user clicks on the sign up button the sign up file is called.

-  The sign_up_gui file shows two input boxes, one to enter the username and one to enter the password, then it uses the signup file to actually creat an account.

-  The login_gui file shows the input boxes, one to enter the username and one to enter the password, then it uses the login file to check if the combination is correct.

-  The login file takes the username and password, hashed the password, it searches and finds the match through the text file(data.txt), checks if the two match

-  The signup file takes the username and password, check the username and password, hash the password and then store the combination in the text file(data.txt).

-  The hashing file takes a string and then hashes the password using an algorithm that is not very good but is made by me, good enough for the purposes of this login system

-  The checks.py file performs some checks which can to see the sign up is done securely and perfectly following all the rules.
  
That's it!

## Status :

In-development, not in condition to use

## Can I contribute ?
Yes

*-Thank you*
________________________________________________________________________________________________________________________________________

Thats it !

Regards,
Navdeep.

### CODE REVIEW

**Comment by Ved-programmer** [comment]
Sure, also by the way, the beginner I am, I messed up by giving response in two places. I trust you by the way. vedrathi2007@gmail.com try to give me a mail right now

**Comment by smartnavdeep** [comment]
Ok

**Comment by Ved-programmer** [comment]
is there any problem in sending email?

**Comment by Ved-programmer** [comment]
What is your mail id?

**Comment by smartnavdeep** [comment]
and drestlessprogrammer@gmail.com

**Pull request merged**
