### PR TITLE
Added the BSD clause three licence

### PR DESCRIPTION
**Pull request by smartnavdeep**
# About the licence

Now this licence is similar to the previous MIT licence, but also has some other conditions.
You won't be able to read the licence here. Here is the licence link (in my fork) : [Clik me](https://github.com/smartnavdeep/Login-System/blob/master/LICENSE)
I hope this is good but if it is not then please feel free to ask.

`- Navdeep`

### CODE REVIEW

**Comment by Ved-programmer** [comment]
how is it different from the mit license? It still allows commercial use and the person still doesn't have to give us credit

**Comment by Ved-programmer** [comment]
I mean like the only thing there is is that the license should be there and in it my name is written but that is also in the mit license

**Comment by smartnavdeep** [comment]
Yeah but when I saw other licenses, hey are very big to read. but I still read most of them and they where abstract and difficult to understand. as I said open source doesn't have that much strong licenses. open source are meant to be copied

**Comment by smartnavdeep** [comment]
Yeah but when I saw other licenses, but they are very big to read. but I still read most of them and they where abstract and difficult to understand. as I said open source doesn't have that much strong licenses. open source are meant to be copied

**Comment by smartnavdeep** [comment]
I by mistakenly have closed it but again opened it.

**Comment by smartnavdeep** [comment]
And the fact that your licence should always be included is indeed stated in both licenses but this one defines it better and when the user reads it, he understands it well.

**Comment by Ved-programmer** [comment]
ok fine. I suggest which ever program or project we make we will always add our names in the software itself. So, if we have a website or a GUI then a button to know about the makers or if it is a command line application then print statements stating that it is us. So that way anyone who uses it would get to know about us

**Comment by Ved-programmer** [comment]
Do the same license pr with the numerical base converter

**Comment by smartnavdeep** [comment]
Yeah Sure.

Regards,
Navdeep.

**Pull request merged**
